### ISSUE TITLE
The name of the Token and the Call sign should be changeable

### ISSUE THREAD

**Issue by GriffGreen** [CharityDAO/MVP#8]
i think in application these 2 things should be parameters for the creator of the campaign to choose... they really can't be the same because there will be multiple tokens for multiple campaigns all using this same contract right?

**Comment by jbaylina** [comment]
technically it's easy. My concern is that this rule goes again the inmitability principal.  If this is necessary in the future, i think it's better to create a new token based on this one.

See the sstoken in the future repository.

**Comment by GriffGreen** [comment]
I like it!
